/*
 
Copyright (c) <2015> <Sungmin YOON>

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.

2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.			

@preserve
Copyright (c) <2015> <???>

??? ?? ??? ???? ?? ???? ?? ??/??? ??? ??? ?? ???.
???? ??. BSD ????? ?? ?????? ???? ??, ?? ????? ??? BSD ????? ??? ?? ???? ??.
?? ??. BSD ????? ?? ?????? ??? ???/??? ??? ??????, ? ??? ?????? ?? ? ??.

3??(3-clause) ?? ????? ???? ?? ?? ??? ????.
????? ??? ??? ?? ??. ??? ?? ?? ?? BSD ?????? ??? ?? ?? ??? ??? BSD ????? ?? ? ???? ?? ? ?? ??? ??? ? ??.

4??(4-clause) ????? ???? ?? ?? ??? ????.
????? ???? ??. BSD ?????? ?? ?? ??? ?(??? ??)? ??? ??? ??? ????? ???? ??.

GPL ??? ???? ???? ??? ????, ??? ??? BSD? ??? ??? ??. BSD ?????? ?? ?? ??? ??? ??? ??? ???? ??? ?? ???. ??? BSD? ???? ?? ???? ??? ??? ???? ??? ??????. MIT ???? ? ????? ???? ???? ?? ??? ????.

??? ???? ?? ????(=?? ??)? ??? ??? ?????? ??? ????? ??? ?? ???, ???? ??(???? ??)??? ???? ??? ???? ???.

4?? ????? ????? ???? ?? ?? ??? GPL? ???? ???.			
*/
var $jscomp={scope:{},findInternal:function(e,q,g){e instanceof String&&(e=String(e));for(var l=e.length,m=0;m<l;m++){var y=e[m];if(q.call(g,y,m,e))return{i:m,v:y}}return{i:-1,v:void 0}}};$jscomp.defineProperty="function"==typeof Object.defineProperties?Object.defineProperty:function(e,q,g){if(g.get||g.set)throw new TypeError("ES3 does not support getters and setters.");e!=Array.prototype&&e!=Object.prototype&&(e[q]=g.value)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.polyfill=function(e,q,g,l){if(q){g=$jscomp.global;e=e.split(".");for(l=0;l<e.length-1;l++){var m=e[l];m in g||(g[m]={});g=g[m]}e=e[e.length-1];l=g[e];q=q(l);q!=l&&null!=q&&$jscomp.defineProperty(g,e,{configurable:!0,writable:!0,value:q})}};
$jscomp.polyfill("Array.prototype.find",function(e){return e?e:function(e,g){return $jscomp.findInternal(this,e,g).v}},"es6-impl","es3");
var sviewLayerCore=function(){function e(){var a=$("#div_modal_loding");a.is(":visible")&&!dataGrid.tran.ajaxLoading&&($("#div_loding").fadeOut(),a.fadeOut(function(){}))}function q(a){if(null==a||a)dataGrid.prop.isProcessing=!1;$("#div_processing").hide();$("#div_modal_processing").hide();dataGrid.prop.isProcessing&&E(null,!1)}var g=/Android|webOS|iPhone|iPad|iPod|BlackBerry|IEMobile|Opera Mini/i.test(navigator.userAgent),l=null,m="",y=null,C=!1,z=999,A=[],E=function(a,c,b){var d=$("#div_modal_processing");
if(null==c||c)dataGrid.prop.isProcessing=!0;if(null==b||b||void 0==b)b={mod:"loding",pos:"loding",hearderUse:"N",div:{c:$("#div_processing"),m:d}},B(b);d.off("click").on("click",function(){"0"==d.css("opacity")&&q()});"function"===typeof a&&setTimeout(function(){d.off("click");try{a()}catch(t){console.clear(),console.log("------------\ud504\ub85c\uc138\uc2f1\uc911 \uc624\ub958 \ubc1c\uc0dd----------\n\n"),console.log(t)}q(c)},100)},O=function(a){var c=null;$(a.div.c).find(".popClose").off("click").on("click",
function(){c=this;u("",c)});var b=!1;if((b=null==a.isModal?!0:a.isModal.isClickClosePopup?!0:!1)&&("N"!=a.hearderUse||null!=a.isModal&&a.isModal.isClickClosePopup))$(a.div.m).off("click").on("click",function(){u("",a.div.c.find(".popClose"))})},B=function(a){"string"==typeof a&&(a=JSON.parse(a));var c=a;if("msg"==a.mod||"conf"==a.mod)a.hearderUse="N";"loding"!=a.mod&&(O(a),$(a.div.c).data("popInfo",c),l=c);"loding"!=a.mod&&("N"==sview.common.util.nvl(a.hearderUse)?$(a.div.c).find(".hearder").hide():
$(a.div.c).find(".hearder").show(),"N"==sview.common.util.nvl(a.footerUse)||sview.common.util.isNull(a.footerUse)?$(a.div.c).find(".popFooter").hide():$(a.div.c).find(".popFooter").show());$(a.div.c).find(".contents").height("");if("url"==a.mod)if(c=a.cnt.replace(/\//g,"").replace(/\./g,""),$(a.div.c).find(".contents").children().not("."+c).hide(),$(a.div.c).find(".contents").children("."+c).show(),"Y"==a.recycling&&0<$("."+c).length)$(a.div.m).show(),$(a.div.c).show(),v(a);else{try{0<$(a.div.c).find(".contents").find("."+
c).length&&$(a.div.c).find(".contents").find("."+c).remove(),$(a.div.c).find(".contents").append("<div class='"+c+"'></div>")}catch(r){}$(a.div.c).find(".contents").find("."+c).load(a.cnt,function(b,c,d){"error"==c?alert("\ud574\ub2f9 \ub9ac\uc18c\uc2a4 \ub85c\ub529 \uc2e4\ud328: \n\n (web/was \uc11c\ubc84 \ud658\uacbd\uc5d0\uc11c\ub9cc \uac00\ub2a5)\n\n xhr.status : "+d.status+"\n\n xhr.statusText : "+d.statusText):($(a.div.m).show(),$(a.div.c).show(),setTimeout(function(){v(a)},100))})}else if("html"==
a.mod){var c=$(a.div.c),b=$(a.div.m),d=null,t=null;if("string"==typeof a.cnt){var h=$(document.createElement("div"));h.append(a.cnt);var f=h.children().eq(0);sview.common.util.isNull(f.attr("id"))?sview.common.util.isNull(f.attr("class"))||(t=$(f).attr("class").split(" ").join(".")):d=$(f).attr("id");h.remove()}else sview.common.util.isNull($(a.cnt).attr("id"))?t=$(a.cnt).attr("class").split(" ").join("."):d=$(a.cnt).attr("id");null!=d?(c.find(".contents").children().not("#"+d).hide(),h=c.find(".contents").children("#"+
d)):(c.find(".contents").children().not("."+t).hide(),h=c.find(".contents").children("."+t));h.show();h.data("isFirstUsePop",!0);if("Y"==a.recycling&&0<c.find(".contents").find("#"+d).length){if(b.show(),c.show(),v(a),sview.common.util.isNull(a.isShowAnimation)||a.isShowAnimation)c.hide(),c.fadeToggle(300)}else"string"==typeof a.cnt?null!=d?c.find(".contents").find("#"+d).remove():null!=t&&c.find(".contents").find("."+t).remove():sview.common.util.isNull(d)?null!=t&&c.find(".contents").find("."+t).remove():
c.find(".contents").find("#"+d).remove(),c.find(".contents").append(a.cnt),b.show(),c.show(),sview.common.util.isNull(d)?(c.find(".contents").children().not("."+t).hide(),h=c.find(".contents").children("."+t)):(c.find(".contents").children().not("#"+d).hide(),h=c.find(".contents").children("#"+d)),h.show(),h.data("isFirstUsePop",!0),v(a),sview.common.util.isNull(a.isShowAnimation)||a.isShowAnimation?(c.hide(),c.fadeToggle(300)):c.show()}else"loding"==a.mod?($(a.div.c).find(".contents").children().remove(),
$(a.div.c).css("opacity",""),$(a.div.m).css("opacity",""),$(a.div.m).show(),$(a.div.c).show(),v(a),setTimeout(function(){$(a.div.m).off("click").on("click",function(){e()})},6E3)):"conf"==a.mod?(c=I(a,1),$(a.div.c).find("div.contents .popAlertStyle").append("<div class='dynamicMsgDiv "+c+"'></div>"),c=$(a.div.c).find("div.contents .popAlertStyle").find(".dynamicMsgDiv."+c),b=sview.message.sviewLayer.msg.msgType7,null!=a.btnTitle&&a.btnTitle.conf&&(b=a.btnTitle.conf),d=sview.message.sviewLayer.msg.msgType8,
null!=a.btnTitle&&a.btnTitle.cancel&&(d=a.btnTitle.cancel),c.html("<span class='span_msg'>"+a.cnt+"<span> <p class='btn'>  <span class='span_no btn-type1'><span>"+d+"</span></span>  <span class='span_yes btn-type2'><span>"+b+"</span></span>  </p>"),c.find(".span_yes").data("rs_row",a),c.find(".span_no").data("rs_row",a),$(a.div.m).show(),$(a.div.c).show(),v(a),$(".span_yes").off("click").on("click",function(){u("Y",this)}),$(".span_no").off("click").on("click",function(){u("N",this)})):(c=I(a,1),
$(a.div.c).find(".contents .popAlertStyle").append("<div class='dynamicMsgDiv "+c+"'></div>"),c=$(a.div.c).find("div.contents .popAlertStyle").find(".dynamicMsgDiv."+c),b=sview.message.sviewLayer.msg.msgType7,null!=a.btnTitle&&a.btnTitle.conf&&(b=a.btnTitle.conf),c.html("<span class='span_msg'>"+a.cnt+"</span> <p class='btn'> <span class='span_yes btn-type2'><span>"+b+"</span></span> </p>"),c.find(".span_yes").data("rs_row",a),$(a.div.m).show(),$(a.div.c).show(),v(a),$(".span_yes").off("click").on("click",
function(){u("",this)}))},I=function(a,c){for(var b="dynamicMsgDivSeq_"+c,d=1;1E3>d&&0!=$(a.div.c).find(".dynamicMsgDiv."+b).length;d++)b="dynamicMsgDivSeq_"+(c+d);return b},v=function(a){var c=null,b=$(a.div.c);b.find(".popTitle:eq(0)").text("");a.title&&b.find(".popTitle:eq(0)").text(a.title);var d=$(window).height(),t=!1,e=function(){if(a.padding){var c="0",e="0",f="0",h="0";"object"!=typeof a.padding?h=f=e=c=a.padding:(c=a.padding.top||"0",e=a.padding.right||"0",f=a.padding.bottom||"0",h=a.padding.left||
"0");b.find(".contents:eq(0)").children().each(function(){var d=$(this);if(d.is(":visible")||"object"==typeof a.cnt&&a.cnt.get(0)==this)d.css({"padding-top":c,"padding-right":e,"padding-bottom":f,"padding-left":h}),b.data("currActiveCnt",d)})}b.find(".contents:eq(0)").children().each(function(){var a=$(this);a.is(":visible")&&b.data("currActiveCnt",a)});var D=$(window).scrollTop(),k,n;"loding"!=a.mod&&"fullScreen"!=a.mod&&(null!=a.width?b.width(a.width):b.width(300),null!=a.height&&b.find(".contents").height(a.height));
("conf"==a.mod||"msg"==a.mod)&&b.height()>d&&b.find(".contents:eq(0)").height(d-20);if("c"==a.pos)k=d/2+$(window).scrollTop()-b.height()/2,n=$(window).width()/2-b.width()/2,b.css({position:"absolute"});else if("g"==a.pos){var p=$(a.obj).offset();k=p.top+$(a.obj).height();n=p.left+$(a.obj).width();b.css({position:"absolute"})}else"p"==a.pos?(!g&&d<b.height()?(t=!0,b.find(".contents").height(d-120),k=(d-b.height())/2):k=d/2-b.height()/2,n=$(window).width()/2-b.width()/2,b.css({position:"fixed"})):"x"==
a.pos?(k=a.top,n=a.left,b.css({position:"absolute"})):"loding"!=a.pos&&(n=k=0,b.css({position:"absolute"}));b.css({top:k,left:n});"html"==a.mod&&"object"==typeof a.cnt&&null==a.height&&b.find(".contents").height("");"g"==a.pos&&(p=$(a.obj).offset(),0<$(".ui-datepicker").length?d<p.top+$(a.obj).height()+($(".ui-datepicker").height()+b.find(".hearder").height())-$(window).scrollTop()&&(k=p.top-($(".ui-datepicker").height()+b.find(".hearder").height()),b.css({top:k,left:n})):(d<p.top+$(a.obj).height()+
b.height()-$(window).scrollTop()&&(k=p.top-b.height(),0>k&&(k=0),b.css({top:k,left:n})),$(window).width()<p.left+$(a.obj).width()+b.width()&&(n=p.left+$(a.obj).width()-b.width(),b.css({top:k,left:n}))));if(g){if("g"==a.pos||"x"==a.pos)n=$(window).width()/2-b.width()/2,b.css({top:k,left:n});p=!1;d<b.height()?(b.data("isMobileReSizeY",!0),b.find(".contents:eq(0)").height(d-b.find(".hearder:eq(0)").height()),b.css({top:0}),p=!0,k="conf"==a.mod||"msg"==a.mod?b.find(".hearder:eq(0)").height()/2:0):k=0;
$(window).width()<b.width()&&(b.data("isMobileReSizeX",!0),b.width($(window).width()),b.css({left:0}),p=!0,n=0);"c"==a.pos&&p&&(b.css({top:k,left:n}),b.css({position:"fixed"}))}$(a.div.m).attr("tabindex",-1).focus();$(window).scrollTop(D)};if("object"===typeof a.cnt)if(0<$(a.cnt).find(".SVIEWedit").length){if("function"==typeof a.successFn&&(a.successFn(a),t&&(b.find(".contents").height(d-120),tempTop=(d-b.height())/2,tempLeft=$(window).width()/2-b.width()/2,b.css({top:tempTop,left:tempLeft}))),e(),
"function"===typeof c&&(c(),c=null),g){var c=$("body").css("overflow"),f=$("body").data("body_overflow");null==f&&($("body").data("body_overflow",c),f=c);$("body").css("overflow","hidden");a.callBackFn_edit_by_mobile=function(){$("body").css("overflow",f)}}}else e(),"function"===typeof c&&(c(),c=null),"function"==typeof a.successFn&&(a.successFn(a),t&&(b.find(".contents").height(d-120),tempTop=(d-b.height())/2,tempLeft=$(window).width()/2-b.width()/2,b.css({top:tempTop,left:tempLeft})));else e(),
"function"===typeof c&&(c(),c=null),"function"==typeof a.successFn&&(a.successFn(a),t&&(b.find(".contents").height(d-120),tempTop=(d-b.height())/2,tempLeft=$(window).width()/2-b.width()/2,b.css({top:tempTop,left:tempLeft})))},u=function(a,c,b){var d=$(c).closest(".popContents").data("popInfo");null==d&&(d=l);if(d)if(sview.common.util.isNull($(c).data("rs_row")))h=function(){var e=d.callBackFn;if("function"==typeof e){var f=$.extend({choiceYN:a,thisBtnObj:c,etcObj:b},d);e(f)}d.callBackFn_edit_by_mobile&&
"function"==typeof d.callBackFn_edit_by_mobile&&d.callBackFn_edit_by_mobile()},f=function(){if(sview.common.util.isNull(d.isModal)||d.isModal)-1<$(d.div.m).attr("id").indexOf("div_modal_")?$(d.div.m).remove():$(d.div.m).hide();-1<$(d.div.c).attr("id").indexOf("div_popContents_")?"Y"==d.recycling?$(d.div.c).hide():$(d.div.c).remove():$(d.div.c).hide()},d.isReverseCallBackFnExe?(f(),h()):(h(),f());else{var e=$(c).data("rs_row"),h=function(){if("function"==typeof e.callBackFn){var b=$.extend({choiceYN:a},
e);e.callBackFn(b)}},f=function(){$(c).closest(".dynamicMsgDiv").remove();0==$(d.div.c).find(".popAlertStyle").children().length&&($(d.div.m).hide(),$(d.div.c).hide())};e.isReverseCallBackFnExe?(f(),h()):(h(),f())}},L=function(a){$("#DYNAMICPOPUP_GL_00001").show()},M=function(){$("#DYNAMICPOPUP_GL_00001").hide();try{pageCommon.setWorkFrameWidth()}catch(a){}},N=function(){m=$("#dynamicPopUpGroupDiv").wrap("<div></div>").parent().html();$("#dynamicPopUpGroupDiv").unwrap();try{edit.property.dynamicPopUpGroupDivHtml=
m}catch(a){}};return{initialize:function(){$("body:last").append("<div id='dynamicPopUpGroupDiv'></div>");$("#dynamicPopUpGroupDiv").append('\x3c!-- \ub3d9\uc801\ud31d\uc5c5 \uba54\uc138\uc9c0(popup.mod : msg, conf) \uc601\uc5ed--\x3e<div id="div_popMsg" class="popContents">\t<div class="hearder">\t\t<button class="popClose" ></button>\t</div>\t<div class="contents">\t\t<div class="popAlertStyle"></div>\t</div></div><div id="div_modal_msg" class="modal_msg"></div>\x3c!-- \ub3d9\uc801\ud31d\uc5c5 \ucee8\ud150\uce20 \uc601\uc5ed --\x3e<div id="div_popContents" class="popContents sviewPopLayers">\t<div class="hearder">\t\t<span class="popTitle"></span>\t\t<button class="popClose" ></button>\t</div>\t<div class="contents"></div>\t<div class="popFooter">\t\t<span class="popReSize"></span>\t</div></div><div id="div_modal" class="modal"></div>\x3c!-- \ub85c\ub529\ubc14 --\x3e<div id="div_loding" class="loding loding_loding"></div><div id="div_modal_loding" class="modal_loding loding_modal"></div>\x3c!-- \ud504\ub85c\uc138\uc2f1\ubc14 --\x3e<div id="div_processing" class="loding processing processing_loding"></div><div id="div_modal_processing" class="modal_loding processing processing_modal"></div>\x3c!-- \ud31d\uc5c5 \ub9ac\uc0ac\uc774\uc988\uc0ac \uc0ac\uc6a9\ud558\ub294 \ud22c\uba85 \ubc31\uadf8\ub77c\uc6b4\ub4dc --\x3e<div id="DYNAMICPOPUP_GL_00001" class="div_mask"></div>\x3c!-- \uc378\ub124\uc77c\uc5d0\uc11c \uc0ac\uc6a9 --\x3e<div id="div_mask_background" class="div_mask"></div>\x3c!-- \ud31d\uc5c5 \uc774\ub3d9/\ub9ac\uc0ac\uc988\uc2dc \ud604\uc7ac \uc0ac\uc774\uc988\uc6a9 \ub354\ubbf8\ub85c \uc0ac\uc6a9 --\x3e<div id="div_popContents_dummy" class="div_mask"></div>\x3c!-- \uc2a4\ud0c0\uc77c\uc5d0 \uc81c\uc57d \ubc1b\uc9c0\uc54a\uace0 \ub3d9\uc791\ud558\ub294 \ub9c8\uc2a4\ud06c(\uc2a4\ud0c0\uc77c \ubcc0\uacbd\uc2dc \uc784\uc758\ub85c \ub6f0\uc6c0 \ucc98\ub9ac \ud558\uae30 \uc704\ud568) --\x3e<div id="sview_div_mask_style" style="position:absolute; top:0px; left:0px; width:150%; height:150%; background:black; display: none; z-index: 9;"></div>');
$(document).undelegate(".popReSize:","mousedown").delegate(".popReSize","mousedown",function(a){var c=$(this);a=c.closest(".popContents");var b=c.closest(".popContents"),d=b.find(".hearder:eq(0)"),e=b.find(".contents:eq(0)"),c=b.find(".popFooter:eq(0)"),h=b.width(),f=b.height(),r=b.css("top"),g=b.css("left"),K=d.height(),w=c.height(),D=$("#DYNAMICPOPUP_GL_00001"),k=$("#div_popContents_dummy");k.width(h);k.height(f);k.css("top",r);k.css("left",g);k.css("position",a.css("position"));a=b.offset();var n=
a.left+h,p=a.top+f,q=!1;D.show();k.show();var l=0,m=0;D.off("mousemove").on("mousemove",function(a){var b=h-(n-a.pageX);a=f-(p-a.pageY);l=100<b?b:100;100<a?m=a-K-w:(a=100,m=100-K-w);q=!0;k.css({width:l,height:a})});D.off("mouseup mouseout").on("mouseup mouseout",function(){$("div.popContents.sviewPopLayers div.hearder").removeClass("popCurr");d.addClass("popCurr");sviewLayerCore.sortLayer(d);q&&(b.css({width:l}),e.css({height:m}));var a=b.find(".SVIEWedit_body");0<a.length&&edit.documentHeightReSizeCallFunction(a);
D.hide();k.hide()})});$(document).undelegate(".popContents .hearder","mousedown").delegate(".popContents .hearder","mousedown",function(a){if($(a.target).hasClass("popClose"))return!0;sviewLayerCore.sortLayer(this);var c=$(this),b=c.closest(".popContents");y=b;$("div.popContents.sviewPopLayers div.hearder").removeClass("popCurr");y.find("div.hearder:eq(0)").addClass("popCurr");var d=b.width(),e=b.height(),h=b.css("top"),f=b.css("left"),r=$("#div_popContents_dummy");r.width(d);r.height(e);r.css("top",
h);r.css("left",f);r.css("position",b.css("position"));var g=0,q=0,w=b.find(".hearder").height(),d=b.find(".popFooter"),l=0,k=!1;d.is(":visible")&&(k=!0,l=d.height());var n=b.find(".contents"),p=b.find(".hearder"),d=$(window),m=d.scrollTop(),v=d.width()/2,u=d.height()/2,F=d.height(),G=d.width(),C=m+F,z=!1,A=!1,B=!1,J=!1,x=b.data("popInfo");L(b);r.show();var H=$("#DYNAMICPOPUP_GL_00001"),c=c.offset(),E=c.top-a.pageY,I=c.left-a.pageX;"p"==x.pos&&(E-=m);H.off("mousemove").mousemove(function(a){p.data("isMove",
!0);C>a.pageY&&(g=E+a.pageY,r.css("top",g));G>a.pageX&&(q=I+a.pageX,r.css("left",q));k&&(z=3>=a.pageX?!0:!1,A=a.pageX>G-3?!0:!1,B=a.pageY<=m+3?!0:!1,J=a.pageY>=C-w-3?!0:!1)});H.off("mouseup mouseout").on("mouseup mouseout",function(a){H.off("mousemove");H.off("mouseup");H.off("mouseout");M();r.hide();try{document.getSelection().removeAllRanges()}catch(P){console.log("9 \ube0c\ub77c\uc6b0\uc838 \ubbf8\uc9c0\uc6d0 : document.getSelection()")}a=p.data("beforeSize");var c=p.data("isMove");c&&b.css({top:g,
left:q});k&&a&&a.isBeforeSize&&c&&(b.css("width",a.width),b.css("height",a.height+w+l),n.css("height",a.height),p.data("beforeSize",{isBeforeSize:!1}));p.data("isMove",!1);if(z){if(null==x.isHalfMode||x.isHalfMode)p.data("beforeSize",{isBeforeSize:!0,width:b.width(),height:$(n).height()}),b.css("width",v),b.css("height",F),n.css("height",F-w-l),b.css("top",m);b.css("left",0);z=!1}if(A){if(null==x.isHalfMode||x.isHalfMode)p.data("beforeSize",{isBeforeSize:!0,width:b.width(),height:$(n).height()}),
b.css("width",v),b.css("height",F),n.css("height",F-w-l),b.css("top",m),b.css("left",G-v);A=!1}B&&(null==x.isHalfMode||x.isHalfMode?(m=$(window).scrollTop(),p.data("beforeSize",{isBeforeSize:!0,width:b.width(),height:$(n).height()}),b.css("width",G),b.css("height",u),n.css("height",u-w-l),b.css("top",m),b.css("left",0)):b.css("top",0),B=!1);if(J){if(null==x.isHalfMode||x.isHalfMode)p.data("beforeSize",{isBeforeSize:!0,width:b.width(),height:$(n).height()}),b.css("width",G),b.css("height",u),n.css("height",
u-w-l),b.css("top",m+u),b.css("left",0);J=!1}})});N();C=!0},openPopUp:function(a){console.log("gfnOpenPopUp \ucf5c >>>>>>>>>>>>>>>>>>> : "+a.callNo);sviewLayerCore.lodingCheckAndExe(function(){$("#sviewDataGridColumnCursorMask").hide();if("msg"==a.mod||"conf"==a.mod)a=$.extend(!0,{div:{c:$("#div_popMsg"),m:$("#div_modal_msg")}},a);else{var c=null,b=null,d=$("#div_popContents");d.css("right","");d.css("bottom","");d.css("opacity","");d.css("box-shadow","");d.css("height","");if(d.is(":visible")){var e=
null,h=null,f=null,r=null,m=!1,g=!1;if("Y"==a.recycling&&"url"==a.mod){var l=a.cnt.replace(/\//g,"").replace(/\./g,"");0<$("."+l).length&&(g=!0,r=$("."+l))}else{null!=a.recycling&&"N"!=a.recycling||"url"!=a.mod?r=$(a.cnt):(l=a.cnt.replace(/\//g,"").replace(/\./g,""),0<$("."+l).length&&(g=!0,r=$("."+l)));var l=$("#dynamicPopUpGroupDiv").find(".contents").find("#"+r.attr("id")),q=!1;0<l.length&&(q=l.data("isFirstUsePop"));"Y"==a.recycling&&q&&(g=!0,r=$(a.cnt))}r&&r.closest(".popContents").get(0)==d.get(0)&&
(g=!1,m=!0);g?(c=r.closest(".popContents"),e=-2,h=Number(c.css("z-index")),f=c.attr("id"),f=f.substr(f.lastIndexOf("_")+1)):(c=d.clone(),c.find(".contents").children().remove(),c.children(":not(.hearder, .contents, .popFooter)").remove());g||(g=c.attr("id"),f=$("div.sviewPopLayers").length,e=0,1==f&&(e=200),h=Number($("div.sviewPopLayers").eq(f-1).css("z-index")),f+=1,c.prop("id",g+"_"+f),c.css("z-index",h+e+2),$("#dynamicPopUpGroupDiv").append(c),m&&c.find(".contents:eq(0)").append(r));if(sview.common.util.isNull(a.isModal)||
a.isModal)b=$("#div_modal").clone(),r=b.attr("id"),b.prop("id",r+"_"+f),b.css("z-index",h+e+1),$("#dynamicPopUpGroupDiv").append(b)}else{if(a.recycling){var k=null,k="url"==a.mod?"."+a.cnt.replace(/\//g,"").replace(/\./g,""):"#"+$(a.cnt).attr("id");$(".sviewPopLayers").each(function(){var a=$(this);if(0<a.find(k).length)return c=a,!1});null==c&&(c=d)}else c=d;b=$("#div_modal")}sview.common.util.isNull(a.isModal)||a.isModal||(b="");a=$.extend(!0,{div:{c:c,m:b}},a)}y=$(a.div.c);$("div.popContents.sviewPopLayers div.hearder").removeClass("popCurr");
y.find("div.hearder:eq(0)").addClass("popCurr");B(a)})},closePopUp:u,openLoding:function(a,c){var b=$("#div_modal_loding");if(!b.is(":visible")&&dataGrid.tran.ajaxLoading)if(b={mod:"loding",pos:"loding",hearderUse:"N",successFn:a,div:{c:$("#div_loding"),m:b}},B(b),window.requestAnimationFrame){var d=function(){window.cancelAnimationFrame(z);dataGrid.tran.ajaxLoading?setTimeout(function(){z=window.requestAnimationFrame(d)},500):(window.cancelAnimationFrame(z),e())};d()}else setTimeout(function(){dataGrid.tran.ajaxLoading||
e()},500)},closeLoding:e,openProcessing:E,closeProcessing:q,getDynamicLayerPopUpHtmlResource:function(){return m},setDynamicLayerPopUpHtmlResource:N,sortLayer:function(a){var c=0,b=null;$("div.sviewPopLayers:visible").each(function(){var a=Number($(this).css("z-index"));isNaN(a)&&(a=0);c<a&&(c=a,b=this)});var d=Number($(a).parent().css("z-index"));$(a).parent().css("z-index",c);$(b).css("z-index",d)},addMask:L,clearMask:M,getCurrPopContents:function(){return y},isLodingDynamicLayerPopUpHtmlResource:function(){return C},
lodingCheckAndExe:function(a){var c=A.length;A.push(c);var b=A[c];window.cancelAnimationFrame(b);var d=function(){C?(window.cancelAnimationFrame(b),a()):setTimeout(function(){b=window.requestAnimationFrame(d)},50)};d()},reSizeMobile:function(){var a=$(window).height();$(".popContents").each(function(){var c=$(this).data("popInfo");if(c){var b=$(c.div.c),d=b.data("isMobileReSizeY"),e=b.data("isMobileReSizeX"),h=!1,f=0,g=0;if(d||$(window).width()==b.height())b.find(".contents:eq(0)").height(a-b.find(".hearder:eq(0)").height()),
b.css({top:0}),h=!0,f="conf"==c.mod||"msg"==c.mod?b.find(".hearder:eq(0)").height()/2:0;e&&(b.width($(window).width()),b.css({left:0}),h=!0,g=0);if("conf"==c.mod||"msg"==c.mod)g=$(window).width()/2-b.width()/2;"c"==c.pos&&h&&(b.css({top:f,left:g}),b.css({position:"fixed"}))}})},getCurrentPopInfo:function(){return l}}}();
$(function(){if(0==$("#link_css_dynamicPopUp_pageStyle").length){var e=sview.common.prop.styleThema+"/sviewLayer.css";$("head").prepend('<link class="pageStyleType" id="link_css_dynamicPopUp_pageStyle" rel="stylesheet" href="'+sview.contextpath.component+"layer/"+e+"?version="+sview.contextpath.SVIEW_VERSION+'" type="text/css">')}sviewLayerCore.initialize()});
